#!/bin/bash

BASE=$(pwd)

# Homebrew
[ -z "$(which brew)" ] &&
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

BREW_PREFIX=${BREW_PREFIX:-$(brew --prefix)}

echo "Updating homebrew"
brew bundle --no-upgrade
echo "Updated homebrew"

"$BASE"/install_asdf
