#!/bin/bash

cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1

BASE=$(pwd)
touch bashrc-extra
mkdir -pv bak

[ $(command -v zsh) ] && $BASE/install_zsh

# dotfiles
for rc in *rc *rc.json tmux.conf tool-versions gitconfig gitignore zprofile zshenv zpath p10k.zsh \
  prettierignore \
  rbenv/default-gems snipaste/config.ini default-*-packages; do
  dir=$(dirname $rc)
  [ $dir != '.' ] && mkdir -pv bak/."$dir"
  mv -v ~/."$rc" bak/."$rc" >/dev/null 2>&1
  ln -sfv "$BASE/$rc" ~/."$rc"
done

# dotdirs
for dir in git_template ctags.d; do
  rm -rf bak/$dir
  mv -v ~/.$dir bak/$dir >/dev/null 2>&1
  
  ln -svf "$BASE/$dir"/ ~/.$dir
done

# git-prompt
if [ ! -e ~/.git-prompt.sh ]; then
  curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh -o ~/.git-prompt.sh
fi

# scripts
mkdir -p ~/bin
for bin in $BASE/bin/*; do
  ln -svf "$bin" ~/bin
done

OS=$(uname -s)
if [ "${OS}" == "Darwin" ]; then
  release="Darwin"
elif [ "${OS}" == "Linux" ]; then
  if [ -f /etc/centos-release ]; then
    release="centos"
  elif [ -f /etc/redhat-release ]; then
    release="rhel"
  elif grep -q -E -i "centos" < /etc/issue; then
    release="centos"
  elif grep -q -E -i "red hat|redhat" < /etc/issue; then
    release="rhel"
  elif grep -q -E -i "debian" < /etc/issue; then
    release="debian"
  elif grep -q -E -i "ubuntu" < /etc/issue; then
    release="ubuntu"
  elif grep -q -E -i "centos" < /proc/version; then
    release="centos"
  elif grep -q -E -i "red hat|redhat" < /proc/version; then
    release="rhel"
  elif grep -q -E -i "debian" < /proc/version; then
    release="debian"
  elif grep -q -E -i "ubuntu" < /proc/version; then
    release="ubuntu"
  elif [ -f /etc/os-release ]; then
    release=$(grep -E "^ID" /etc/os-release | awk -F '=' '{print $2}')
  fi
fi

if [ "$release" == "Darwin" ]; then
  "$BASE"/install_osx
fi

[ ! -d ~/.asdf ] && git clone https://github.com/asdf-vm/asdf.git ~/.asdf

mkdir -p ~/.rbenv/plugins
if [ ! -e ~/.rbenv/plugins/rbenv-default-gems ]; then
  git clone https://github.com/rbenv/rbenv-default-gems.git ~/.rbenv/plugins/rbenv-default-gems
fi
if [ ! -e ~/.rbenv/plugins/rbenv-ctags ]; then
  git clone https://github.com/tpope/rbenv-ctags.git ~/.rbenv/plugins/rbenv-ctags
fi
