#!/bin/sh

set -u -o pipefail

echo "installing oh-my-zsh..."

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" >/dev/null 2>&1

echo "installed oh-my-zsh"

read -r -d '' plugins <<EOF
source ~/.zshrc
dir=\${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
[ ! -e \$dir ] && git clone https://github.com/zsh-users/zsh-autosuggestions \$dir

dir=\${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
[ ! -e \$dir ] && git clone https://github.com/zsh-users/zsh-syntax-highlighting \$dir

dir=\${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/themes/powerlevel10k
[ ! -e \$dir ] && git clone --depth=1 https://github.com/romkatv/powerlevel10k \$dir
return 0
EOF

zsh -c "$plugins"
