#!/bin/bash

cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1

BASE=$(pwd)
touch bashrc-extra
mkdir -pv bak

[ $(command -v zsh) ] && $BASE/install_zsh

# dotfiles
for rc in *rc *rc.json tmux.conf tool-versions gitconfig gitignore zprofile zshenv zpath p10k.zsh \
  prettierignore \
  rbenv/default-gems snipaste/config.ini default-*-packages; do
  dir=$(dirname $rc)
  [ $dir != '.' ] && mkdir -pv bak/."$dir"
  mv -v ~/."$rc" bak/."$rc" >/dev/null 2>&1
  ln -sfv "$BASE/$rc" ~/."$rc"
done

# dotdirs
for dir in git_template ctags.d; do
  rm -rf bak/$dir
  mv -v ~/.$dir bak/$dir >/dev/null 2>&1
  
  ln -svf "$BASE/$dir"/ ~/.$dir
done

# git-prompt
if [ ! -e ~/.git-prompt.sh ]; then
  curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh -o ~/.git-prompt.sh
fi

# scripts
mkdir -p ~/bin
for bin in $BASE/bin/*; do
  ln -svf "$bin" ~/bin
done

if [ "$(uname -s)" = 'Darwin' ]; then
  # Homebrew
  [ -z "$(which brew)" ] &&
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

  echo "Updating homebrew"
  brew install --cask iterm2 snipaste squirrel \
    qlcolorcode qlimagesize qlmarkdown qlstephen qlvideo quicklook-json quicklookase \
    telegram firefox raycast macvim 

  brew tap homebrew/cask-fonts
  brew install --cask font-hack-nerd-font

  brew install \
    fd ripgrep cmake git imagemagick gnupg fzf \
    ranger tree wget zsh jq go highlight bat \
    rbenv node yarn \
    mysql postgresql redis \
    pinentry-mac bash-completion tmux \
    translate-shell \
    shellcheck shfmt

  brew tap universal-ctags/universal-ctags
  brew install --HEAD universal-ctags

  # install fzf
  $(brew --prefix)/opt/fzf/install
fi

[ ! -d ~/.asdf ] && git clone https://github.com/asdf-vm/asdf.git ~/.asdf

mkdir -p ~/.rbenv/plugins
if [ ! -e ~/.rbenv/plugins/rbenv-default-gems ]; then
  git clone https://github.com/rbenv/rbenv-default-gems.git ~/.rbenv/plugins/rbenv-default-gems
fi
if [ ! -e ~/.rbenv/plugins/rbenv-ctags ]; then
  git clone https://github.com/tpope/rbenv-ctags.git ~/.rbenv/plugins/rbenv-ctags
fi
