#!/bin/sh

BASE=$(dirname "$0")
[ -f ~/.vimrc ] && mv -v ~/.vimrc "$(dirname "$(pwd)")"/bak
if type vim &>/dev/null;then
  vim +PlugInstall +qall
fi

if type nvim &>/dev/null;then
  nvim --headless +PlugInstall +qall
fi

