#!/bin/sh

BASE=$(dirname "$0")
[ -f ~/.vimrc ] && mv -v ~/.vimrc "$(dirname "$(pwd)")"/bak
if type vim &>/dev/null;then
  # https://github.com/junegunn/vim-plug/issues/730#issuecomment-363037250
  vim +'PlugInstall --sync' +qall &> /dev/null
fi

if type nvim &>/dev/null;then
  nvim --headless +Lazy restore +qall
fi

rm -f ~/.config/nvim 2> /dev/null
rm -rf ~/.config/nvim 2> /dev/null

ln -svf "$BASE"/ ~/.config/nvim
