#!/bin/bash

set -x
cd "$(dirname "$(dirname "$(realpath "${BASH_SOURCE[0]}")")")" || exit 1
BASE=$(pwd)
RIME_DIR=${1:-~/Library/Rime}
VERSION=$(cat "$BASE"/rime/upstream_version)

# 保存 sync 文件夹
if [ -d "$RIME_DIR/sync"  ]; then
  mv -v "$RIME_DIR/sync" "$BASE"/tmp/sync
fi

# 下载仓库
rm -rf "$BASE"/tmp/Rime
git clone --depth 1 --branch "$VERSION" https://github.com/gaboolic/rime-frost "$BASE"/tmp/Rime

rm -rf "$RIME_DIR"
ln -sf "$BASE"/tmp/Rime "$RIME_DIR"

for file in rime/custom/*; do
  if [ ! -d "$BASE/$file" ]; then
    [ -e "$RIME_DIR/$file" ] && mv -v "$RIME_DIR/$file" bak/"$file"
    ln -sfv "$BASE/$file" "$RIME_DIR/$(basename "$file")"
  fi
done

for file in rime/opencc/*; do
  [ -e "$RIME_DIR/file" ] && mv -v "$RIME_DIR/$file" bak/"$file"
  ln -sfv "$BASE/$file" "$RIME_DIR/opencc/$(basename "$file")"
done

ln -sf "$BASE"/tmp/Rime/rime_frost.dict.yaml "$RIME_DIR"/pinyin_flypy.dict.yaml

if [ -e "$HOME/.mybackups" ]; then
  ln -sf "$(cat "$HOME/.mybackups")/rime" "$HOME/Library/Rime/sync"
fi

mv -v "$BASE"/tmp/sync "$RIME_DIR/sync"
rm -rf "$BASE"/tmp/sync
