#!/bin/bash

cd "$(dirname "$(dirname "$(realpath "${BASH_SOURCE[0]}")")")" || exit 1
BASE=$(pwd)

# Homebrew
[ -z "$(which brew)" ] &&
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

BREW_PREFIX=${BREW_PREFIX:-$(brew --prefix)}

# https://x.com/beihuo/status/1899249930289733723
# https://macos-defaults.com/
setup_macos_defaults() {
  echo "==========================================================="
  echo "               Setting up macOS Defaults...                "
  echo "-----------------------------------------------------------"
  # {{{ dock
  defaults write com.apple.dock "autohide" -bool "true"
  defaults write com.apple.dock "show-recents" -bool "false"

  killall Dock
  # }}}

  # {{{ finder
  # 设置文件夹在顶部
  defaults write com.apple.finder "_FXSortFoldersFirst" -bool "true"

  # 搜索当前文件夹
  defaults write com.apple.finder "FXDefaultSearchScope" -string "SCcf"

  # Show hidden files in Finder
  defaults write com.apple.finder "AppleShowAllFiles" -bool "true"

  # Disable the warning when changing a file extension
  defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

  # Finder 显示文件扩展名
  defaults write NSGlobalDomain AppleShowAllExtensions -bool true

  # Finder 使用 list 视图
  defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

  # Finder 使用绝对时间
  # https://gist.github.com/rxliuli/629da07479b70d6235088828cdb1bd8f
  defaults write com.apple.finder RelativeDates -bool false
  defaults write NSGlobalDomain AppleICUDateFormatStrings -dict-add "1" "yyyy-MM-dd HH:mm"
  defaults write NSGlobalDomain AppleICUDateFormatStrings -dict-add "2" "yyyy-MM-dd HH:mm:ss"
  defaults write NSGlobalDomain AppleICUDateFormatStrings -dict-add "3" "yyyy-MM-dd HH:mm:ss"
  defaults write NSGlobalDomain AppleICUDateFormatStrings -dict-add "4" "yyyy-MM-dd HH:mm:ss"

  killall Finder
  # }}}

  # {{{ Menu bar
  # Show time in menu bar
  defaults write com.apple.menuextra.clock "DateFormat" -string "\"EEE d MMM HH:mm:ss\""
  defaults write com.apple.menuextra.clock ShowSeconds -bool true
  defaults write com.apple.menuextra.clock "FlashDateSeparators" -bool "true"
  killall SystemUIServer
  # }}}

  # {{{ keyboard
  defaults write NSGlobalDomain com.apple.keyboard.fnState -bool true

  # 按键重复速度(长按删除键的时候这个的执行速度，越短越快)
  defaults write -g KeyRepeat -int 2

  # 按键重复延迟(按住一个字母后等多久会变成一直输入)
  defaults write -g InitialKeyRepeat -int 15
  # }}}

  # {{{ misc
  defaults write NSGlobalDomain AppleMeasurementUnits -string Centimeters

  # 日期显示采用 24 小时制
  defaults write NSGlobalDomain AppleICUForce24HourTime -bool true

  # 温度显示摄氏度
  defaults write -g AppleTemperatureUnit -string Celsius

  # 禁止 mac 系统的文本替换 [参考链接](https://github.com/element-hq/element-web/issues/7155) 和他类似，之所以不删除 macOS 上的文本替换，是因为文本替换会在 iOS 和 macOS 之间同步，iOS 端会将替换内容上到候选词里面，不会误触。但是在 macOS 上直接就触发了替换，非常影响使用。
  defaults write -g WebAutomaticTextReplacementEnabled -int 0

  # 释放快捷键 ⌘Command+D (需要重启) [参考链接](https://apple.stackexchange.com/questions/22785/how-do-i-disable-the-command-control-d-word-definition-keyboard-shortcut-in-os-x)
  defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 70 '<dict><key>enabled</key><false/></dict>'

  # 支持简单密码
  pwpolicy -clearaccountpolicies

  # 使用三指拖动
  defaults write com.apple.AppleMultitouchTrackpad "TrackpadThreeFingerDrag" -bool "true"

  # }}}

  # {{{ 3rd party
  # https://github.com/artginzburg/MiddleClick-Ventura#number-of-fingers
  defaults write com.rouge41.middleClick fingers 5
  osascript -e 'tell application "System Events" to make login item at end with properties {path:"/Applications/MiddleClick.app", hidden:true}'
  # }}}

  echo "macOS defaults have been updated!"
}

ln -sf "$BASE"/raycast/scripts/extra-code-from-mail.applescript "~/Library/Application Scripts/com.apple.mail/"
setup_macos_defaults

echo "Updating homebrew"
brew bundle --no-upgrade
echo "Updated homebrew"

"$BASE"/scripts/install_asdf
"$BASE"/rime/install ~/Library/Rime
