#!/bin/bash

cd "$(dirname "$(dirname "${BASH_SOURCE[0]}")")" || exit 1
BASE=$(pwd)

# Homebrew
[ -z "$(which brew)" ] &&
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

BREW_PREFIX=${BREW_PREFIX:-$(brew --prefix)}

echo "Updating homebrew"
brew bundle --no-upgrade
echo "Updated homebrew"

"$BASE"/scripts/install_asdf
"$BASE"/scripts/install_rime ~/Library/Rime

# https://github.com/artginzburg/MiddleClick-Ventura#number-of-fingers
defaults write com.rouge41.middleClick fingers 5
osascript -e 'tell application "System Events" to make login item at end with properties {path:"/Applications/MiddleClick.app", hidden:true}'
