#!/bin/bash

# tmux plugins
if [ -x ~/.tmux/plugins/tpm/bin/install_plugins ]; then
  echo "Installing tmux plugins"
  ~/.tmux/plugins/tpm/bin/install_plugins >/dev/null 2>&1 || true
fi

echo "Installed tmux"
