[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
  type = "git-repo"
  url = "https://github.com/zsh-users/zsh-autosuggestions"
  refreshPeriod = "72h"
  clone.args = ["--filter=blob:none"]
  pull.args = ["--ff-only"]

[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
  type = "git-repo"
  url = "https://github.com/zsh-users/zsh-syntax-highlighting"
  refreshPeriod = "72h"
  clone.args = ["--filter=blob:none"]
  pull.args = ["--ff-only"]

[".oh-my-zsh/custom/plugins/fzf-tab"]
  type = "git-repo"
  url = "https://github.com/Aloxaf/fzf-tab"
  refreshPeriod = "72h"
  clone.args = ["--filter=blob:none"]
  pull.args = ["--ff-only"]

[".oh-my-zsh/custom/themes/powerlevel10k"]
  type = "git-repo"
  url = "https://github.com/romkatv/powerlevel10k"
  refreshPeriod = "72h"
  clone.args = ["--filter=blob:none"]
  pull.args = ["--ff-only"]
