# https://mise.jdx.dev/configuration.html
[tools]
# https://github.com/jdx/mise/blob/main/registry.toml
bat = "latest"
dust = "latest"
fd = "latest"
neovim = "latest"
rg = "latest"
shellcheck = "latest"
usage = "latest"

[settings]
go_set_gobin = true
status.missing_tools = "never"
