# https://mise.jdx.dev/configuration.html
[tools]
# https://github.com/jdx/mise/blob/main/registry.toml
usage = "latest"
neovim = "latest"

[settings]
go_set_gobin = true
status.missing_tools = "never"
